name: Regiland Valley
author: Anuruddha Premalal
baseurl: 
description: Anuruddha's Personal Blog
github: http://www.github.com/apremalal
twitter: http://www.twitter.com/apremalal
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com/in/apremalal/
email: anuruddhapremalal[at]gmail.com
location: 42°2'16"N   70°12'47"W
disqus: apremall
google_analytics: UA-58427055-2

highlighter: rouge
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
